// Candidate aesthetic/style vocabulary for zero-shot CLIP classification.
// CLIP can only pick from this list — it doesn't invent labels — so keep it broad.
export const STYLE_LABELS = [
  "surrealism",
  "minimalism",
  "maximalism",
  "brutalism",
  "cottagecore",
  "dark academia",
  "y2k",
  "cyberpunk",
  "vaporwave",
  "film noir",
  "art deco",
  "bauhaus",
  "grunge",
  "punk",
  "gothic",
  "romantic",
  "pastel",
  "monochrome",
  "high contrast",
  "moody",
  "dreamy",
  "whimsical",
  "industrial",
  "rustic",
  "luxury",
  "streetwear",
  "vintage",
  "retro-futurism",
  "psychedelic",
  "abstract",
  "geometric",
  "organic shapes",
  "botanical",
  "nautical",
  "urban",
  "editorial",
  "candid",
  "cinematic",
  "ethereal",
  "kitsch",
  "glitch art",
  "flat illustration",
  "vector illustration",
  "graphic design poster",
  "duotone",
  "risograph print",
  "editorial illustration",
  "flat design",
  "halftone print",
  "collage",
  "pop art",
  "impressionism",
  "expressionism",
  "photorealism",
  "line art",
  "watercolor",
  "neon",
  "pastel goth",
  "coastal",
  "normcore",
  "high fashion",
  "avant-garde",
  "art nouveau",
  "mid-century modern",
  "scandinavian design",
  "wabi-sabi",
  "earth tones",
  "high saturation",
  "desaturated",
  "grainy film",
  "polaroid",
  "analog",
  "3d render",
  "architecture",
  "interior design",
  "typography",
  "street photography",
  "portrait photography",
  "landscape photography",
  "still life",
] as const;
